---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://quay.io/jetstack/charts/trust-manager
  ref:
    tag: "v0.22.1"
    digest: "sha256:893e8438a0013dcc027a1e5a8237f4062d37738e700c4ec2795b29eb2288dc49"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 15m
  timeout: 5m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: trust-manager
  values:
    app:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 256Mi
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
      metrics:
        service:
          enabled: true
          servicemonitor:
            enabled: true
    secretTargets:
      enabled: true
      authorizedSecrets:
      - ca-certificates
      - cilium-mitm-trust-bundle
