---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-mitm-cert-deptrack
  namespace: infra-security
spec:
  commonName: deptrack.k8s.mcathome.ch
  dnsNames:
  - crates.io
  - epss.cyentia.com
  - epss.empiricalsecurity.com
  - github.com
  - api.github.com
  - nvd.nist.gov
  - proxy.golang.org
  - pypi.org
  - registry.npmjs.org
  - rubygems.org
  - repository.jboss.org
  - packages.atlassian.com
  - repo.clojars.org
  - maven.google.com
  - osv-vulnerabilities.storage.googleapis.com
  - dl.google.com
  - '*.nvd.nist.gov'
  - '*.maven.org'
  - '*.pkg.dev'
  issuerRef:
    name: cilium-mitm-ca
    kind: ClusterIssuer
  secretName: cilium-mitm-cert-deptrack
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-dependency-track-egress
  namespace: infra-security
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: dependency-track-api-server
  egress:
  - toFQDNs:
    - matchName: crates.io
    - matchName: epss.cyentia.com
    - matchName: epss.empiricalsecurity.com
    - matchName: github.com
    - matchName: api.github.com
    - matchName: nvd.nist.gov
    - matchName: proxy.golang.org
    - matchName: pypi.org
    - matchName: registry.npmjs.org
    - matchName: rubygems.org
    - matchName: repository.jboss.org
    - matchName: packages.atlassian.com
    - matchName: repo.clojars.org
    - matchName: maven.google.com
    - matchName: osv-vulnerabilities.storage.googleapis.com
    - matchName: dl.google.com
    - matchPattern: '*.nvd.nist.gov'
    - matchPattern: 'repo*.maven.org'
    - matchPattern: 'europe-*-docker.pkg.dev'
    toPorts:
    - ports:
      - port: '443'
        protocol: TCP
      terminatingTLS:
        secret:
          name: cilium-mitm-cert-deptrack
          namespace: infra-security
      originatingTLS:
        secret:
          name: ca-certificates
          namespace: cert-manager
      rules:
        http:
        - method: GET
