---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-storage
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: infra-storage
spec:
  interval: 1h30m
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: v0.0.31
  ignore: |-
    /*
    !/deploy/chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: infra-storage
spec:
  interval: 10m0s
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: infra-storage
      interval: 10m0s
  values:
    storageClass:
      create: true
      defaultClass: true
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/mnt/