apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  creationTimestamp: "2025-04-30T20:12:49Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: infra-security
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: kubescape
  namespace: infra-security
  resourceVersion: "24807123"
  uid: ba0519ba-db5e-4d0b-8aed-770ee55652ca
spec:
  chart:
    spec:
      chart: kubescape-operator
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: infra-security
      version: 1.27.x
  driftDetection:
    mode: enabled
  interval: 10m0s
  values:
    clusterName: mcathome
    components:
      otelCollector:
        enabled: false
      nodeAgent:
        enabled: false
    configurations:
      otelUrl: grpc://otel-collector-opentelemetry-collector.infra-observability:4317
      persistence: enable
    ksNamespace: infra-security
    kubescape:
      serviceMonitor:
        enable: true
    logger:
      name: json
    nodeAgent:
      serviceMonitor:
        enable: true
status:
  conditions:
  - lastTransitionTime: "2025-04-30T20:12:51Z"
    message: Running 'install' action with timeout of 5m0s
    observedGeneration: 1
    reason: Progressing
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2025-04-30T20:12:51Z"
    message: Running 'install' action with timeout of 5m0s
    observedGeneration: 1
    reason: Progressing
    status: Unknown
    type: Ready
  helmChart: infra-security/infra-security-kubescape
  lastAttemptedConfigDigest: sha256:bc1eae49dd093e5c7f10406d9752ff98370520066fe84d06df9c472b260e5438
  lastAttemptedGeneration: 1
  lastAttemptedRevision: 1.27.3
  observedGeneration: -1
  storageNamespace: infra-security
