---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: infra-security
spec:
  interval: 1h30m
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: infra-security
spec:
  interval: 1h30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: falco
      version: 4.21.x
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: infra-security
      interval: 10m0s
  values:
    scc:
      create: false

    tolerations: []

    metrics:
      enabled: true
      outputRule: true

    kubernetes:
      enabled: true

    serviceMonitor:
      create: true

    grafana:
      dashboards:
        enabled: true
        configMaps:
          falco:
            folder: Security

    falco:
      webserver:
        prometheus_metrics_enabled: true
      metrics:
        enabled: true
      priority: warning

    falcosidekick:
      enabled: true
      replicaCount: 1
      webui:
        enabled: true
        replicaCount: 1
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      grafana:
        dashboards:
          enabled: true
          configMaps:
            falcosidekick:
              folder: Security
      config:
        discord:
          webhookurl: ${discordFalcoAddress}
        loki:
          grafanaDashboard:
            enabled: true
            configMap:
              folder: Security