---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: infra-security
spec:
  interval: 1h30m
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: infra-security
spec:
  interval: 1h30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: falco
      version: 7.0.x
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: infra-security
      interval: 10m0s
  values:
    scc:
      create: false

    tolerations: []

    metrics:
      enabled: true
      outputRule: true

    kubernetes:
      enabled: true

    serviceMonitor:
      create: true

    grafana:
      dashboards:
        enabled: true
        configMaps:
          falco:
            folder: Security

    falco:
      webserver:
        prometheus_metrics_enabled: true
      metrics:
        enabled: true
      priority: warning

    customRules:
      # https://falco.org/docs/concepts/rules/overriding/
      # https://falco.org/docs/concepts/rules/exceptions/
      rule-overrides.yaml: |-
        - rule: Drop and execute new binary in container
          append: true
          exceptions:
            - name: cilium
              fields: [evt.type, proc.cmdline, proc.exe]
              comps: [=, contains, =]
              values:
                - [execve, cilium-cni, /opt/cni/bin/cilium-cni]

    falcosidekick:
      enabled: true
      replicaCount: 1
      webui:
        enabled: true
        replicaCount: 1
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      grafana:
        dashboards:
          enabled: true
          configMaps:
            falcosidekick:
              folder: Security
      config:
        discord:
          webhookurl: ${discordFalcoAddress}
        loki:
          hostport: http://loki.infra-observability:3100
          grafanaDashboard:
            enabled: true
            configMap:
              folder: Security