---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelRepository
metadata:
  name: kubescape
  namespace: infra-security
spec:
  interval: 1h30m
  url: https://kubescape.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: infra-security
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: kubescape-operator
      version: 1.27.x
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: infra-security
      interval: 10m0s
  values:
    clusterName: ${clusterName}
    ksNamespace: infra-security

    logger:
      name: json

    components:
      otelCollector:
        enabled: false

    configurations:
      otelUrl: grpc://otel-collector-opentelemetry-collector.infra-observability:4317
      persistence: enable

    kubescape:
      serviceMonitor:
        enable: true
      
    nodeAgent:
      serviceMonitor:
        enable: true