---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aquasec
  namespace: infra-security
spec:
  interval: 1h30m
  url: https://aquasecurity.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: infra-security
spec:
  interval: 1h30m
  driftDetection: 
    mode: enabled
  chart:
    spec:
      chart: trivy-operator
      version: 0.27.x
      sourceRef:
        kind: HelmRepository
        name: aquasec
        namespace: infra-security
      interval: 10m0s
  values:
    targetWorkloads: ""

    operator:
      builtInTrivyServer: true
    
      webhookBroadcastURL: ${discordTrivyAddress}

      # Enable all metrics for the moment to test
      # TODO: disable some again due to cardinality
      metricsFindingsEnabled: true
      metricsVulnIdEnabled: true
      metricsExposedSecretInfo: true
      metricsConfigAuditInfo: true
      metricsRbacAssessmentInfo: true
      metricsInfraAssessmentInfo: true
      metricsImageInfo: true
      metricsClusterComplianceInfo: true

    serviceMonitor:
      enabled: true
    
    nodeCollector:
      volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
          readOnly: true
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
        - name: var-lib-kube-scheduler
          mountPath: /var/lib/kube-scheduler
          readOnly: true
        - name: var-lib-kube-controller-manager
          mountPath: /var/lib/kube-controller-manager
          readOnly: true
        # https://www.talos.dev/v1.10/learn-more/architecture/#the-file-system
        # - name: etc-systemd
        #   mountPath: /etc/systemd
        #   readOnly: true
        - name: lib-systemd
          mountPath: /lib/systemd/
          readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        - name: etc-cni-netd
          mountPath: /etc/cni/net.d/
          readOnly: true
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: /var/lib/etcd
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: var-lib-kube-scheduler
          hostPath:
            path: /var/lib/kube-scheduler
        - name: var-lib-kube-controller-manager
          hostPath:
            path: /var/lib/kube-controller-manager
        # - name: etc-systemd
        #   hostPath:
        #     path: /etc/systemd
        - name: lib-systemd
          hostPath:
            path: /lib/systemd
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
        - name: etc-cni-netd
          hostPath:
            path: /etc/cni/net.d/