#---
#apiVersion: cilium.io/v2
#kind: CiliumClusterwideNetworkPolicy
#metadata:
#  name: allow-all
#spec: 
#  endpointSelector: {} 
#  ingress: 
#  - fromEntities: 
#    - all
#  egress:
#  - toEntities: 
#    - all
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: dns
spec:
  endpointSelector: {}
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
      rules:
        dns:
        - matchPattern: "*"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ingress
  namespace: kube-system
  labels:
    name: hubble-ui
spec:
  entryPoints: 
  - websecure
  routes:
  - match: Host(`${hubbleHostName}`)
    kind: Rule
    services:
      - name: hubble-ui
        port: 80
  tls: {}

