---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: kyverno-policies
      version: 3.3.x
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 10m0s
  values:
    validationFailureAction: Audit

    policyExclude:
      disallow-host-path:
        any:
          - resources:
              kinds:
                - DaemonSet
              namespaces:
                - infra-observability
              names:
                - '*node-exporter'
                - 'vector'
      disallow-host-namespaces:
        any:
          - resources:
              kinds:
                - DaemonSet
              namespaces:
                - infra-observability
              names:
                - '*node-exporter'