---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sync.yaml
  - cleanup-policies.yaml
  - verifying-policies.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: kyverno
    unsetOnly: true
