---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: kyverno-policies
      version: 3.8.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 10m0s
  values:
    validationFailureAction: Audit

    policyExclude:
      disallow-host-path:
        any:
        - resources:
            kinds:
            - DaemonSet
            - Pod
            namespaces:
            - infra-observability
            - infra-security
            names:
            - '*node-exporter*'
            - 'vector*'
            - 'node-collector*'
            - 'falco-*'
      disallow-host-namespaces:
        any:
        - resources:
            kinds:
            - DaemonSet
            - Pod
            namespaces:
            - infra-observability
            - infra-security
            names:
            - '*node-exporter*'
            - 'node-collector*'
      disallow-privileged-containers:
        any:
        - resources:
            kinds:
            - DaemonSet
            - Pod
            namespaces:
            - infra-security
            names:
            - 'falco-*'
---
apiVersion: policies.kyverno.io/v1
kind: DeletingPolicy
metadata:
  name: cleanup-finished-pods
  annotations:
    policies.kyverno.io/title: Remove Finished Pods
    policies.kyverno.io/category: Cluster Maintenance
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/severity: info
    policies.kyverno.io/description: >-
      This policy removes 'dead' pods which occur after e.g. a talos node reboot.
      Normally they would be removed with:
      kubectl delete pod --field-selector=status.phase==Succeeded -A
      kubectl delete pod --field-selector=status.phase==Failed -A
spec:
  schedule: '0 * * * *'
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        resources: ['pods']
  conditions:
    - name: pod-is-finished
      expression: >
        object.status.phase == 'Succeeded' || object.status.phase == 'Failed'
---
apiVersion: policies.kyverno.io/v1
kind: DeletingPolicy
metadata:
  name: cleanup-failed-jobs
  annotations:
    policies.kyverno.io/title: Delete Failed Jobs
    policies.kyverno.io/category: Cluster Maintenance
    policies.kyverno.io/subject: Job
    policies.kyverno.io/severity: info
    policies.kyverno.io/description: >-
      This policy removes failed jobs as soon as there has been a more recent
      successful job execution.
spec:
  schedule: '0 1 * * *'
  matchConstraints:
    resourceRules:
      - apiGroups: [batch]
        apiVersions: [v1]
        resources: [jobs]
    objectSelector:
      matchLabels:
        k8s.mcathome.ch/cleanup: 'true'
  conditions:
    - name: job-has-failures
      expression: >
        object.status.?failed.orValue(0) > 0