---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: whoami-auto-instrumentation
  namespace: traefik
spec:
  exporter:
    endpoint: http://jaeger.infra-observability:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  initContainerSecurityContext:
    privileged: true
    runAsUser: 0
