ipam:
  mode: kubernetes
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
hostFirewall:
  enabled: true
hubble:
  relay:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi
  ui:
    enabled: true
    backend:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 512Mi
    frontend:
      resources:
        requests:
          cpu: 5m
          memory: 16Mi
        limits:
          cpu: 25m
          memory: 64Mi
  tls:
    auto:
      method: cronJob
envoy:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  log:
    format: null
    format_json:
      date: '%Y-%m-%dT%T.%e'
      thread_id: '%t'
      source_line: '%s:%#'
      level: '%l'
      logger: '%n'
      message: '%j'
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1.5Gi

operator:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 512Mi
