---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: user-playground
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-policy
  interval: 10m0s
  path: ./applications/user-playground
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s