---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cluster-variables
  path: ./infrastructure/storage
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-storage
  path: ./infrastructure/observability
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-observability
  interval: 10m0s
  path: ./infrastructure/controllers
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 10m0s
  path: ./infrastructure/configs
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s