# https://docs.siderolabs.com/kubernetes-guides/monitoring-and-observability/deploy-metrics-server
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1h30m
  url: https://kubernetes-sigs.github.io/metrics-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 15m
      version: 3.13.0
  values:
    args:
      - --kubelet-insecure-tls
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
