---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-variables
  namespace: flux-system
spec:
  url: ssh://git@github.com/bossm8/k8s-playground-vars.git
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: k8s-playground-vars
  ignore: |-
    /*
    !/variables
    !/configs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-variables
  namespace: flux-system
spec:
  interval: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./variables
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-variables
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-configs
  namespace: flux-system
spec:
  interval: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-variables
  timeout: 5m0s