---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    tag: "v1.20.2"
    digest: "sha256:294a761ca972ea11ae79b9219960ca13a5337a1cbb550604c151586d266159eb"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 15m
  timeout: 5m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    securityContext:
      runAsUser: 10002
    podLabels:
      k8s.mcathome.ch/allow-kube-api: 'true'
    startupapicheck:
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
    cainjector:
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
    webhook:
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
