---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reloader
  namespace: infra-reloader
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/stakater/charts/reloader
  ref:
    tag: "2.2.12@sha256:1efe694acf4ada31404232a1889126ddc92789bddca3054f74f3b2e8ded1116a"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: infra-reloader
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: reloader
  values:

    reloader:
      logFormat: json
      readOnlyRootFilesystem: true
      enableMetricsByNamespace: true

      podMonitor:
        enabled: true

      deployment:
        labels:
          k8s.mcathome.ch/allow-kube-api: 'true'
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault

        containerSecurityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
