---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-observability

resources:
  - job.yaml
  - rbac.yaml
  - netpol.yaml

configMapGenerator:
  - name: find-script
    files:
      - assets/find.sh

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: nova
      k8s.mcathome.ch/component: release-watcher
      k8s.mcathome.ch/application: nova
