---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-mitm-cert-nova
  namespace: infra-observability
spec:
  commonName: nova.k8s.mcathome.ch
  dnsNames:
  - artifacthub.io
  - ghcr.io
  - mirror.gcr.io
  - quay.io
  - reg.kyverno.io
  - registry.k8s.io
  - registry.gitlab.com
  - '*.docker.io'
  issuerRef:
    name: cilium-mitm-ca
    kind: ClusterIssuer
  secretName: cilium-mitm-cert-nova
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-nova-find
  namespace: infra-observability
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: nova
  egress:
  - toFQDNs:
    - matchName: artifacthub.io
    - matchName: ghcr.io
    - matchName: mirror.gcr.io
    - matchName: quay.io
    - matchName: reg.kyverno.io
    - matchName: registry.k8s.io
    - matchName: registry.gitlab.com
    - matchPattern: '*.docker.io'
    toPorts:
    - ports:
      - port: '443'
        protocol: TCP
      terminatingTLS:
        secret:
          name: cilium-mitm-cert-nova
          namespace: infra-observability
      originatingTLS:
        secret:
          name: ca-certificates
          namespace: cert-manager
      rules:
        http: [{}]
