---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: otel-operator
  namespace: infra-observability
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-operator
  ref:
    tag: "0.114.1"
    digest: "sha256:31e45d1c475d47749358c746a9d6948dd8e00f8f4d02890ca3d5a4ccd8d50c2b"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: infra-observability
spec:
  interval: 15m
  timeout: 5m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: otel-operator
  values:
    admissionWebhooks:
      certManager:
        enabled: true

    manager:
      serviceMonitor:
        enabled: true
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
      extraArgs:
      - --enable-nginx-instrumentation
