---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      extraVolumes:
        - name: crowdsec-bouncer-plugin
          emptyDir: {}
      extraInitContainers:
        - name: init-clone-crowdsec-bouncer
          image: crowdsecurity/lua-bouncer-plugin
          imagePullPolicy: IfNotPresent
          env:
            # TODO: Use safer approach to expose secrets (e.g. vault)
            - name: API_URL
              value: "${csApiUrl}"
            - name: API_KEY
              value: "${csApiKeyNginx}"
            - name: BOUNCER_CONFIG
              value: "/crowdsec/crowdsec-bouncer.conf"
            - name: BAN_TEMPLATE_PATH
              value: /etc/nginx/lua/plugins/crowdsec/templates/ban.html
            - name: CAPTCHA_TEMPLATE_PATH
              value: /etc/nginx/lua/plugins/crowdsec/templates/captcha.html

            - name: APPSEC_URL
              value: "${csAppSecUrl}"
            - name: APPSEC_FAILURE_ACTION
              value: passthrough
            - name: APPSEC_CONNECT_TIMEOUT
              value: "100"
            - name: APPSEC_SEND_TIMEOUT
              value: "100"
            - name: APPSEC_PROCESS_TIMEOUT
              value: "1000"
            - name: ALWAYS_SEND_TO_APPSEC
              value: "false"

          command: ['sh', '-c', "apk add --no-cache bash; /bin/bash /docker_start.sh; mkdir -p /lua_plugins/crowdsec/; cp -R /crowdsec/* /lua_plugins/crowdsec/"]
          volumeMounts:
            - name: crowdsec-bouncer-plugin
              mountPath: /lua_plugins
          securityContext:
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      extraVolumeMounts:
        - name: crowdsec-bouncer-plugin
          mountPath: /etc/nginx/lua/plugins/crowdsec
          subPath: crowdsec
      config:
        plugins: "crowdsec"
        lua-shared-dicts: "crowdsec_cache: 50m"
        server-snippet : |
          resolver local=on ipv6=off;