
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
spec:
  values:
    experimental:
      plugins:
        crowdsec-bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.4.1
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: crowdsec
        spec:
          plugin:
            crowdsec-bouncer:
              enabled: true
              logLevel: INFO

              crowdsecLapiHost: ${csApiUrl}
              crowdsecLapiScheme: http
              crowdsecLapiKey: ${csApiKeyTraefik}

              crowdsecAppsecEnabled: true
              crowdsecAppsecHost: ${csAppSecUrl}
              crowdsecAppsecFailureBlock: false
              crowdsecAppsecUnreachableBlock: false
