---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h30m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ingress-nginx
      # Use 4.11 for now to enable crowdsec which requires lua
      version: 4.11.x
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 10m0s
  values:
    controller:
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
        proxy-real-ip-cidr: "${proxyIP},10.244.0.0/16"
        enable-opentelemetry: "true"
        otlp-collector-host: otel-collector-opentelemetry-collector.infra-observability

        log-format-escape-json: "true"
        log-format-upstream: '{
            "@timestamp": "$time_iso8601",
            "remote_ip": "$remote_addr",
            "remote_user": "$remote_user",
            "request": "$request",
            "status": "$status",
            "response_size": "$body_bytes_sent",
            "referer": "$http_referer",
            "user_agent": "$http_user_agent",
            "request_size_total": "$request_length",
            "request_time": "$request_time",
            "proxy_upstream_name": "$proxy_upstream_name",
            "upstream_addr": "$upstream_addr",
            "upstream_status": "$upstream_status",
            "upstream_response_size_total": "$upstream_response_length",
            "upstream_response_time": "$upstream_response_time",
            "traceparent": "$opentelemetry_context_traceparent",
            "trace_id": "$opentelemetry_trace_id",
            "span_id": "$opentelemetry_span_id",
            "req_id": "$req_id"
          }'

      service:
        enabled: true
        type: NodePort
        nodePorts:
          http: 31080
          https: 31443

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
