---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-traefik
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
spec:
  interval: 1h30m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: traefik
      version: 34.4.x
      sourceRef:
        kind: HelmRepository
        name: ingress-traefik
        namespace: ingress-traefik
      interval: 10m0s
  values:

    ingressClass:
      enabled: true
      isDefaultClass: false

    experimental:
      plugins:
        crowdsec-bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.4.1

    gateway:
      enabled: false

    metrics:
      addInternals: true
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: ${prometheusReleaseLabel}

    tracing:
      addInternals: false
      serviceName: traefik8s
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: otel-collector-opentelemetry-collector.infra-observability:4317
          insecure: true

    logs:
      access:
        enabled: true

    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`${traefikHostName}`)
        entryPoints:
          - websecure
        middlewares:
          - name: traefik-dashboard-redirect
            namespace: ingress-traefik

    ports:
      traefik:
        port: 8000
      web:
        port: 8080
        nodePort: 30080
        proxyProtocol:
          trustedIPs:
            - ${proxyIP}
      websecure:
        port: 8443
        nodePort: 30443
        proxyProtocol:
          trustedIPs:
            - ${proxyIP}

    service:
      type: NodePort

    tlsOptions:
      default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_CHACHA20_POLY1305_SHA256
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-redirect
  namespace: ingress-traefik
spec:
  redirectRegex:
    regex: ^(https?://[^/]*)(/dashboard)?(/)?$
    replacement: $${1}/dashboard/