---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-traefik
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
spec:
  interval: 1h30m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: traefik
      version: 34.4.x
      sourceRef:
        kind: HelmRepository
        name: ingress-traefik
        namespace: ingress-traefik
      interval: 10m0s
  values:
    ingressClass:
      enabled: true
      isDefaultClass: false
    experimental:
      plugins:
        crowdsec-bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.4.1
    gateway:
      enabled: false
    metrics:
      addInternals: true
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        port: 8080
        nodePort: 30080
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        nodePort: 30443
    service:
      type: NodePort
    tlsOptions:
      default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_CHACHA20_POLY1305_SHA256
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: crowdsec
        spec:
          plugin:
            crowdsec-bouncer:
              enabled: true
              logLevel: INFO

              crowdsecLapiHost: ${csApiUrl}
              crowdsecLapiScheme: http
              crowdsecLapiKey: ${csApiKeyTraefik}

              crowdsecAppsecEnabled: true
              crowdsecAppsecHost: ${csAppSecUrl}
              crowdsecAppsecFailureBlock: false
              crowdsecAppsecUnreachableBlock: false
