---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h30m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ingress-nginx
      # Use 4.11 for now to enable crowdsec which requires lua
      version: 4.11.x
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 10m0s
  values:
    controller:
      # hostPort:
      #   enabled: true
      service:
        type: NodePort
        ports: 
          http: 8080
          https: 8443
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true
    