---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-nginx.yaml
  - ingress-traefik.yaml
  - cert-manager.yaml

patches:
  - path: cs-ingress-nginx.yaml
  - path: cs-ingress-traefik.yaml
