---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-reloader
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: infra-reloader
spec:
  url: https://stakater.github.io/stakater-charts
  interval: 1h30m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: infra-reloader
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: reloader
      version: 2.0.x
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: infra-reloader
      interval: 10m0s
  values:

    reloader:
      logFormat: json

      readOnlyRootFilesystem: true

      enableMetricsByNamespace: true

      serviceMonitor:
        enabled: true
