---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-observability

resources:
  - prometheus.yaml
  - notifications.yaml
  - alertmanager.yaml

configMapGenerator:
  - name: flux-crs-metrics
    files:
      - values.yaml=flux-crs-metrics.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: grafana-sc-dashbaords
    files:
      - values.yaml=grafana-sc-dashboards.yaml
    options:
      labels:
        app.kubernetes.io/part-of: grafana
        app.kubernetes.io/component: monitoring

configurations:
  - kustomizeconfig.yaml
