---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-observability
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: infra-observability
spec:
  interval: 1h30m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${prometheusReleaseLabel}
  namespace: infra-observability
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ${prometheusReleaseLabel}
      version: 69.6.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: infra-observability
      interval: 10m0s
  values:
    global:
      rbac:
        create: true
        pspEnabled: true
    prometheusOperator:
      extraArgs:
        - --labels="cluster=${clusterName}"
    prometheus:
      prometheusSpec:
        externalLabels:
          cluster: ${clusterName}
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 15Gi
        retention: 14d
        retentionSize: 14.5GiB
    alertmanager:
      alertmanagerSpec:
        storage: 
          volumeClaimTemplate:
            spec:
              accessModes: 
                - ReadWriteOnce
              resources:
                  requests:
                    storage: 3Gi
    grafana:
      enabled: true
    nodeExporter:
      enabled: true
      operatingSystems:
        linux:
          enabled: true
        aix:
          enabled: false
        darwin:
          enabled: false
    kubeEtcd:
      endpoints:
        - ${singleNodeClusterIP}