---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-variables
  namespace: flux-system
spec:
  interval: 10m
  serviceAccountName: kustomize-controller
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./variables
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-configs
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-networking-policies
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  dependsOn:
    - name: cluster-variables
  path: ./infrastructure/networking/policies
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: ConfigMap
        name: dev-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  dependsOn:
    - name: cluster-variables
  path: ./infrastructure/controllers/storage
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: ConfigMap
        name: dev-vars
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-crds
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  dependsOn:
    - name: cluster-variables
  path: ./infrastructure/observability/metrics/crds
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-configs
  namespace: flux-system
spec:
  interval: 10m
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-observability-crds
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
  path: ./configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-configs
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-security-trivy
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-observability-traces
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/security/trivy
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-security-deptrack
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-security-trivy
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/security/deptrack
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-certs-cm
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-observability-crds
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/controllers/certs/cert-manager
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-certs-tm
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-controllers-certs-cm
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/controllers/certs/trust-manager
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-certs-config
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-controllers-certs-tm
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/controllers/certs/config
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-networking-cni
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-controllers-certs-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/networking/cni/dev
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-policy
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-networking-cni
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/controllers/policy/release
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-policy-config
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-controllers-policy
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/controllers/policy/config
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-metrics
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  dependsOn:
    - name: infra-networking-cni
  path: ./infrastructure/observability/metrics/release
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-traces
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  dependsOn:
    - name: infra-networking-cni
  path: ./infrastructure/observability/traces
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-probes
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-observability-metrics
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/observability/probes
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-logs
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-networking-cni
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/observability/logs
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-releases
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-networking-cni
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/observability/releases
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-backup
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-observability-metrics
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/observability/backup
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-ingress
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-observability-traces
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/controllers/ingress/dev
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-reloader
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-networking-cni
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: dev-vars
  interval: 1m
  path: ./infrastructure/controllers/reloader
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
