---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-configs
  namespace: flux-system
spec:
  url: ssh://git@github.com/bossm8/k8s-playground-configs.git
  interval: 10m
  ref:
    branch: main
  secretRef:
    name: k8s-playground-vars
  ignore: |-
    /*
    !/variables
    !/configs
