---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium-system

resources:
  - ../base

configMapGenerator:
  - name: cilium-helm-dev
    files:
      - values.yaml=./values.yaml

patchesJson6902:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: cilium
    patch: |-
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: ConfigMap
          name: cilium-helm-dev
