---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  # Use flux-system to use valuesFrom with values from the vars repo
  namespace: flux-system
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 9.3.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: infra-observability
      interval: 10m0s

  valuesFrom:
    - kind: ConfigMap
      name: blackbox-targets
      targetPath: serviceMonitor.targets 

  values:
    namespaceOverride: infra-observability

    config:
      modules:
        http_2xx:
          prober: http
          timeout: 30s
          http:
            method: GET
            follow_redirects: true
        http_401:
          prober: http
          timeout: 30s
          http:
            method: GET
            valid_status_codes: [401]
            follow_redirects: true

    prometheusRule:
      enabled: true
      rules:
        - alert: BlackboxProbeFailed
          expr: probe_success == 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: >-
              Blackbox probe failed (instance {{ index $labels "instance" }})
            description: |
              Blackbox exporter failed to probe {{ index $labels "instance" }}
    
    serviceMonitor:
      enabled: true
      defaults:
        module: http_2xx
        interval: 2m30s
      selfMonitor:
        enabled: true
