---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-blackbox-exporter
  namespace: infra-observability
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
  ref:
    tag: "11.11.0"
    digest: "sha256:47e3c299bd82db9a02f30223859919fa4a3bea13ed6c556d4828e76d09251658"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: infra-observability
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: prometheus-blackbox-exporter

  values:

    config:
      modules:
        http_2xx:
          prober: http
          timeout: 30s
          http:
            method: GET
            follow_redirects: true
        http_4xx:
          prober: http
          timeout: 30s
          http:
            method: GET
            valid_status_codes: [401, 404]
            follow_redirects: true

    prometheusRule:
      enabled: true
      namespace: infra-observability
      rules:
        - alert: BlackboxProbeFailed
          expr: 'probe_success == 0'
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: >-
              Blackbox probe failed (instance {{ index $labels "instance" }})
            description: |
              Blackbox exporter failed to probe {{ index $labels "instance" }}

    serviceMonitor:
      enabled: true
      defaults:
        module: http_2xx
        interval: 2m30s
      selfMonitor:
        enabled: true