---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/kyverno/charts/kyverno
  ref:
    tag: "3.8.1"
    digest: "sha256:61d8cd025a27bd2962e1a6daf40fc98218a97ca2164f1184d14f41d40db84efa"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 15m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: kyverno
  values:

    crds:
      migration:
        enabled: false

    features:
      logging:
        format: json
      backgroundScan:
        # https://kyverno.io/docs/installation/customization/#resource-filters
        # Need to use resource filters, else the specified exluded namespaces
        # are still included in background scans
        skipResourceFilters: false

    grafana:
      enabled: true
      annotations:
        grafana_dashboard_folder: Kyverno

    admissionController:
      serviceMonitor:
        enabled: true
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
        k8s.mcathome.ch/allow-tracing: 'true'
      tracing:
        enabled: true
        address: jaeger.infra-observability
        port: 4317
      container:
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

    backgroundController:
      serviceMonitor:
        enabled: true
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
        k8s.mcathome.ch/allow-tracing: 'true'
      tracing:
        enabled: true
        address: jaeger.infra-observability
        port: 4317
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
       # Need additional permissions
       # https://kyverno.io/docs/installation/customization/#customizing-permissions
       # admission webhook "validate-policy.kyverno.svc" denied the request:
       # path: spec.rules[0].generate..:
       # system:serviceaccount:kyverno:kyverno-background-controller requires
       # permissions get for resource rbac.authorization.k8s.io/v1/RoleBinding
       # in namespace {{ request.object.metadata.name }}
      rbac:
        clusterRole:
          extraResources:
            - apiGroups: ["rbac.authorization.k8s.io"]
              resources: ["rolebindings"]
              verbs: ["get"]

    cleanupController:
      serviceMonitor:
        enabled: true
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
        k8s.mcathome.ch/allow-tracing: 'true'
      tracing:
        enabled: true
        address: jaeger.infra-observability
        port: 4317
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 320Mi
      rbac:
        clusterRole:
          extraResources:
            # Needed to cleanup 'dead' pods (see policies.yaml#L43)
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "watch", "list", "delete"]
            - apiGroups: ["batch"]
              resources: ["jobs"]
              verbs: ["get", "watch", "list", "delete"]

    reportsController:
      serviceMonitor:
        enabled: true
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
        k8s.mcathome.ch/allow-tracing: 'true'
      tracing:
        enabled: true
        address: jaeger.infra-observability
        port: 4317
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
