---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: policy-reporter
  namespace: kyverno
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/kyverno/charts/policy-reporter
  ref:
    tag: "3.7.4@sha256:34d3086c7f9adfa94636d6aec5e4c3e9c3ff041499dcce7d4f6005850c58b33b"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: kyverno
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: policy-reporter
  values:

    metrics:
      enabled: true

    podLabels:
      k8s.mcathome.ch/allow-kube-api: 'true'

    logging:
      encoding: json
      logLevel: 4

    target:
      discord:
        name: discord
        webhook: ${discordKyvernoAddress}
        minimumSeverity: info

    ui:
      enabled: true
      ingress:
        enabled: true
        className: traefik
        hosts:
        - host: ${policyReporterHostName}
          paths:
          - path: /
            pathType: ImplementationSpecific
        tls: []
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'
        k8s.mcathome.ch/allow-traefik-ingress: 'true'
      logging:
        encoding: json

    monitoring:
      enabled: true
      grafana:
        dashboards:
          multicluster:
            enabled: false
        folder:
          annotation: grafana_dashboard_folder
          name: Kyverno

    plugin:
      kyverno:
        enabled: true
        podLabels:
          k8s.mcathome.ch/allow-kube-api: 'true'
        logging:
          encoding: json
      trivy:
        enabled: true
        podLabels:
          k8s.mcathome.ch/allow-kube-api: 'true'

    sourceFilters:
      - selector:
          source: kyverno
        uncontrolledOnly: false
        disableClusterReports: false
        kinds:
          exclude: [ReplicaSet]