---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trivy-operator
  namespace: infra-security
spec:
  interval: 1h30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/aquasecurity/helm-charts/trivy-operator
  ref:
    tag: "0.32.1"
    digest: "sha256:39caa565eaac9388bf5d86b9853e7535ae41703b4068475ea553c3e97754c06f"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy
  namespace: infra-security
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: trivy-operator
  values:
    # https://aquasecurity.github.io/trivy-operator/v0.21.0/docs/vulnerability-scanning/trivy/
    targetWorkloads: ""

    operator:
      builtInTrivyServer: true
      podLabels:
        k8s.mcathome.ch/allow-kube-api: 'true'

      scanJobsConcurrentLimit: 4

      # Or use postee: https://aquasecurity.github.io/postee/
      webhookBroadcastURL: http://sbom-to-deptrack.infra-security:8080
      webhookBroadcastTimeout: 120s
      webhookSendDeletedReports: true

      sbomGenerationEnabled: true
      metricsFindingsEnabled: true

    serviceMonitor:
      enabled: true

    trivy:
      mode: Standalone
      podLabels:
        k8s.mcathome.ch/allow-traefik-ingress: 'true'

    trivyOperator:
      scanJobCompressLogs: false
      scanJobTolerations:
      - effect: NoSchedule
        operator: Exists

    nodeCollector:
      volumeMounts:
      - name: var-lib-etcd
        mountPath: /var/lib/etcd
        readOnly: true
      - name: var-lib-kubelet
        mountPath: /var/lib/kubelet
        readOnly: true
      - name: var-lib-kube-scheduler
        mountPath: /var/lib/kube-scheduler
        readOnly: true
      - name: var-lib-kube-controller-manager
        mountPath: /var/lib/kube-controller-manager
        readOnly: true
      - name: etc-kubernetes
        mountPath: /etc/kubernetes
        readOnly: true
      - name: etc-cni-netd
        mountPath: /etc/cni/net.d/
        readOnly: true
      volumes:
      - name: var-lib-etcd
        hostPath:
          path: /var/lib/etcd
      - name: var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: var-lib-kube-scheduler
        hostPath:
          path: /var/lib/kube-scheduler
      - name: var-lib-kube-controller-manager
        hostPath:
          path: /var/lib/kube-controller-manager
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: etc-cni-netd
        hostPath:
          path: /etc/cni/net.d/
