---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno-policy-reporter
  namespace: kyverno
spec:
  interval: 1h30m
  url: https://kyverno.github.io/policy-reporter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policy-reporter
  namespace: kyverno
spec:
  interval: 10m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: policy-reporter
      version: 3.7.x
      sourceRef:
        kind: HelmRepository
        name: kyverno-policy-reporter
        namespace: kyverno
      interval: 10m0s
  values:

    metrics:
      enabled: true

    logging:
      encoding: json
      logLevel: -1

    target:
      discord:
        name: discord
        webhook: ${discordKyvernoAddress}
        minimumSeverity: info

    ui:
      enabled: true
      logging:
        encoding: json

    monitoring:
      enabled: true
      grafana:
        dashboards:
          multicluster:
            enabled: false
        folder:
          annotation: grafana_dashboard_folder
          name: Kyverno

    plugin:
      kyverno:
        enabled: true
        logging:
          encoding: json
      trivy:
        enabled: true

    sourceFilters:
      - selector:
          source: kyverno
        uncontrolledOnly: false
        disableClusterReports: false
        kinds:
          exclude: [ReplicaSet]