---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nova-find
spec:
  schedule: "* 0 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 300
      template:
        spec:
          serviceAccountName: nova-find
          automountServiceAccountToken: true
          containers:
          - name: nova
            image: quay.io/fairwinds/nova:v3.11.3
            imagePullPolicy: IfNotPresent
            command:
              - /bin/sh
              - /scripts/find.sh
            securityContext:
              runAsUser: 10001
              runAsGroup: 10001
              runAsNonRoot: true
              readOnlyRootFilesystem: true
              privileged: false
              allowPrivilegeEscalation: false
              seccompProfile: 
                type: RuntimeDefault
              capabilities:
                drop:
                - ALL
            volumeMounts:
              - mountPath: /workspace
                name: workspace
              - mountPath: /scripts
                name: find-script
                readOnly: true
            workingDir: /workspace
            resources:
              requests:
                cpu: '0.2'
                memory: '5Mi'
              limits:
                cpu: '0.5'
                memory: '10Mi'
          restartPolicy: OnFailure
          volumes:
            - name: workspace
              emptyDir: {}
            - name: find-script
              projected:
                defaultMode: 0777
                sources:
                - configMap:
                    name: find-script

