---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-observability

resources:
  - job.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: find-script
    files:
      - find.sh

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

labels:
  - includeSelectors: false
    pairs:
      k8s.mcathome.ch/component: update-notifier
      k8s.mcathome.ch/application: nova
