# https://git-scm.com/docs/git-http-backend
ServerName git-daemon
Listen 8080

LoadModule cgid_module modules/mod_cgid.so

DocumentRoot /var/www/git

SetEnv GIT_PROJECT_ROOT /var/www/git
SetEnv GIT_HTTP_EXPORT_ALL
SetEnv REMOTE_USER $REDIRECT_REMOTE_USER

ScriptAlias /git/ /usr/libexec/git-core/git-http-backend/

<Directory "/usr/libexec/git-core">
  Options +ExecCGI
  Require all granted
</Directory>

<Directory "/var/www/git">
  Require all granted
</Directory>

ErrorLog /dev/stderr
CustomLog /dev/stdout combined